### ISSUE TITLE
Fail to compile simple kv_cache

### ISSUE THREAD

**Issue by maxbartel** [iree-org/iree-turbine#85]
Hi! I am having trouble compiling a simple kv_cache module. Here is the example code

```python
import torch
from iree.turbine import aot

class KVCache(torch.nn.Module):
    def __init__(
        self,
        max_batch_size,
        max_seq_length,
        n_heads,
        head_dim,
        dtype=torch.float32,
    ):
        super().__init__()
        cache_shape = (max_batch_size, n_heads, max_seq_length, head_dim)
        self.register_buffer("k_cache", torch.zeros(cache_shape, dtype=dtype))
        self.register_buffer("v_cache", torch.zeros(cache_shape, dtype=dtype))

    def forward(self, input_pos, k_val, v_val):
        # input_pos: [S], k_val: [B, H, S, D]
        assert input_pos.shape[0] == k_val.shape[2]

        k_out = torch.ops.aten.index_put_(self.k_cache, [None, None, input_pos], k_val)
        v_out = torch.ops.aten.index_put_(self.v_cache, [None, None, input_pos], v_val)

        return k_out, v_out
    

max_batch_size = 512
max_seq_length = 512
n_heads = 16
head_dim = 16
dtype = torch.float32

kv_cache = KVCache(max_batch_size, max_seq_length, n_heads, head_dim, dtype)

S = 10
input_pos = torch.arange(S)

B = max_batch_size
H = n_heads
D = head_dim

k_val = torch.randn(B, H, S, D, dtype=dtype)
v_val = torch.randn(B, H, S, D, dtype=dtype)


# Example inputs for torch.export.export
initialize_inputs = (max_batch_size, max_seq_length, n_heads, head_dim)
inputs = (input_pos, k_val, v_val)

# Now, to use with torch.export.export
fx_imported = torch.export.export(KVCache(*initialize_inputs), args=inputs)
print(fx_imported)

# Fails
aot.export(fx_imported)
```

This fails with error message 

```
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, b_k_cache: "f32[512, 16, 512, 16]", b_v_cache: "f32[512, 16, 512, 16]", input_pos: "i64[10]", k_val: "f32[512, 16, 10, 16]", v_val: "f32[512, 16, 10, 16]"):
             # File: /Users/bartel/Documents/torchchat/test.py:22 in forward, code: k_out = torch.ops.aten.index_put_(self.k_cache, [None, None, input_pos], k_val)
            index_put: "f32[512, 16, 512, 16]" = torch.ops.aten.index_put.default(b_k_cache, [None, None, input_pos], k_val);  b_k_cache = k_val = None
            
             # File: /Users/bartel/Documents/torchchat/test.py:23 in forward, code: v_out = torch.ops.aten.index_put_(self.v_cache, [None, None, input_pos], v_val)
            index_put_1: "f32[512, 16, 512, 16]" = torch.ops.aten.index_put.default(b_v_cache, [None, None, input_pos], v_val);  b_v_cache = input_pos = v_val = None
            return (index_put, index_put_1, index_put, index_put_1)
            
Graph signature: ExportGraphSignature(input_specs=[InputSpec(kind=<InputKind.BUFFER: 3>, arg=TensorArgument(name='b_k_cache'), target='k_cache', persistent=True), InputSpec(kind=<InputKind.BUFFER: 3>, arg=TensorArgument(name='b_v_cache'), target='v_cache', persistent=True), InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='input_pos'), target=None, persistent=None), InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='k_val'), target=None, persistent=None), InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='v_val'), target=None, persistent=None)], output_specs=[OutputSpec(kind=<OutputKind.BUFFER_MUTATION: 3>, arg=TensorArgument(name='index_put'), target='k_cache'), OutputSpec(kind=<OutputKind.BUFFER_MUTATION: 3>, arg=TensorArgument(name='index_put_1'), target='v_cache'), OutputSpec(kind=<OutputKind.USER_OUTPUT: 1>, arg=TensorArgument(name='index_put'), target=None), OutputSpec(kind=<OutputKind.USER_OUTPUT: 1>, arg=TensorArgument(name='index_put_1'), target=None)])
Range constraints: {}

ERROR 08-16 13:16:05 [ir_utils.py:200] module failed to verify (dumping to /var/folders/14/qwn8vwc11fg1sjdsg80kq47w0000gn/T/turbine_module_builder_error.mlir)
Traceback (most recent call last):
  File "/Users/bartel/Documents/sharktank/deps/shark-turbine/shark_turbine/aot/support/ir_utils.py", line 215, in finalize_construct
    self.module_op.verify()
iree.compiler._mlir_libs._site_initialize.<locals>.MLIRError: Verification failed:
error: "/Users/bartel/Documents/torchchat/test.py":22:0: 'util.global.store' op global "__auto.constant_512_16_512_16_torch.float32" is not mutable and cannot be stored to
 note: "/Users/bartel/Documents/torchchat/test.py":22:0: see current operation: "util.global.store"(%7) <{global = @__auto.constant_512_16_512_16_torch.float32}> : (tensor<512x16x512x16xf32>) -> ()
Traceback (most recent call last):
  File "/Users/bartel/Documents/torchchat/test.py", line 56, in <module>
    aot.export(fx_imported)
  File "/Users/bartel/Documents/sharktank/deps/shark-turbine/shark_turbine/aot/exporter.py", line 321, in export
    cm = TransformedModule(context=context, import_to="import")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bartel/Documents/sharktank/deps/shark-turbine/shark_turbine/aot/compiled_module.py", line 654, in __new__
    module_builder.finalize_construct()
  File "/Users/bartel/Documents/sharktank/deps/shark-turbine/shark_turbine/aot/support/ir_utils.py", line 215, in finalize_construct
    self.module_op.verify()
iree.compiler._mlir_libs._site_initialize.<locals>.MLIRError: Verification failed:
error: "/Users/bartel/Documents/torchchat/test.py":22:0: 'util.global.store' op global "__auto.constant_512_16_512_16_torch.float32" is not mutable and cannot be stored to
 note: "/Users/bartel/Documents/torchchat/test.py":22:0: see current operation: "util.global.store"(%7) <{global = @__auto.constant_512_16_512_16_torch.float32}> : (tensor<512x16x512x16xf32>) -> ()
```

Is this a bug or am I using the API wrong?

 I am suprised that the buffers are not marked as mutable since the graph signature seems to capture that with `OutputSpec(kind=<OutputKind.BUFFER_MUTATION: 3>, arg=TensorArgument(name='index_put_1'), target='v_cache')`

Thank you for the help!

**Comment by maxbartel** [comment]
@stellaraccident Do you maybe have an idea here?

**Comment by stellaraccident** [comment]
This might be the first use case of buffers being used like this. I wired them up when the parameters were going in and I think there is a test of using frozen buffers but probably not all together with mutation.

Fwiw, this should work, but also for most of our work on this, we've ended up not using buffers for this but mutable parameters. Primarily because it allows the calling program to manage multiple instances and supports dynamic shapes. 

I would need to retrace steps on how this gets here, but here is the breadcrumb: https://github.com/iree-org/iree-turbine/blob/3fb9a5f98566d991ff551eee1d3f419c053b6975/shark_turbine/aot/support/procedural/exported_program.py#L223

When handing an ExportedProgram, the generic FxImporter in torch-mlir manipulates these backend features via a Hooks class. How buffers are materialized to globals comes in there but need to do some stepping through. I imagine it is just blindly creating globals as immutable vs checking what the metadata was for.

**Comment by maxbartel** [comment]
This got me on the correct path. However `resolve_literal` already needs the information ff the tensor gets overwritten, because it decides if it gets materialized as a `util.global` or a` torch.vtensor`. For this we will need to change the hook signature. I will try to open the two PRs for that next week.
